### ISSUE TITLE
1.13 complete data?

### ISSUE THREAD

**Issue by uncovery** [PrismarineJS/minecraft-assets#3]
Is the 1.13 data complete? I see no dark_oak_fence.png. dark_oak_fence_gate.png for example.

**Comment by rom1504** [comment]
Ah indeed it seems to be missing. Anything that is null in
https://github.com/PrismarineJS/minecraft-assets/blob/master/data/1.13/blocks_textures.json#L2745
is missing.
For some things such as bed it's normal because the texture is "builtin"
but maybe fence is missing for other reasons. I'll look into it.
